<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MyGenie" failures="0" tests="6" name="testRunner.TestRunner" time="57.336" errors="1" timestamp="2024-12-17T14:07:01 CST" skipped="0">
  <testcase classname="testRunner.TestRunner" name="runScenario" time="9.747"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="8.423">
    <error message="Error initializing Excel data: Fail to save: an error occurs while saving the package : The part /xl/worksheets/sheet2.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@6a4c36b7. Enable logging via Log4j 2 for more details." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Error initializing Excel data: Fail to save: an error occurs while saving the package : The part /xl/worksheets/sheet2.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@6a4c36b7. Enable logging via Log4j 2 for more details.
at appHook.Hooks.setUp(Hooks.java:35)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRunner" name="runScenario" time="9.521"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="9.519"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="9.715"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="10.411"/>
</testsuite> <!-- testRunner.TestRunner -->
